blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://discord.gg/horsenuggets
    about: Please ask and answer questions here.
  - name: Project Channel
    url: https://youtube.com/HorseNuggets
    about: Subscribe to the horse himself!
